### PR TITLE
Refactor commands 

### PR DESCRIPTION
**Pull request by lex111**
Hi @andrewscaya, I hope you are well,

History: about a year ago, I expressed a [desire to work on improving your project](https://github.com/linuxforphp/linuxforcomposer/issues/1)... And finally, I start doing refactoring, although maybe it doesn't make much sense, because it's just refactoring :smiley: 

Anyway, this is only the first part of refactoring that I have planned. I want to split the codebase so that I end up making the commands easier to maintain and understand.

In this PR:

- Introduce base class for commands `BaseCommand` to reduce code duplication (methods for Windows).
- Use strict compassion everywhere
- Rename variables to match camelCase variables convention
- Minor improvements to naming methods and variables
- Use array destructuring (_this is controversial, but in the second step work I will think about it._)

Diff changes aren't  big, so it shouldn't be hard to examine. Please take some time for them, I want to continue what I started.

### CODE REVIEW

**Comment by andrewscaya** [comment]
@lex111 Excellent! I'll certainly review your PR next week! Many thanks! :)

**Comment by andrewscaya** [comment]
Many thanks @lex111 ! I'll be merging your PR to branch 2.0.10-dev. Your changes will therefore be included in the next release of Linux for Composer!

**Comment by andrewscaya** [comment]
Merged on 2.0.10-dev, commit f9e8e2c37cca530e1128e7b1766a609ecc85fa85.

**Comment by lex111** [comment]
@andrewscaya great, but I will continue refactoring in next PRs, as I wrote earlier, these are not final changes.

**Comment by lex111** [comment]
@andrewscaya unfortunately this year I will not have time to finish my planned refactoring. Therefore, I will do it already in 2021!
Happy holidays! :christmas_tree:

**Comment by andrewscaya** [comment]
👍

**Pull request closed without merging**
