### PR TITLE
Updated composer.json PHP Requirements

### PR DESCRIPTION
**Pull request by dbierer**
Modified PHP requirements in `composer.json` to support PHP 8

### CODE REVIEW

**Comment by andrewscaya** [comment]
Included in version 2.0.9.1.

@dbierer Many thanks!

**Comment by andrewscaya** [comment]
@dbierer Thought you had followed the syntax for Sphinx in the documentation, but I see it's not the case: https://linux-for-composer.readthedocs.io/en/latest/usage.html. Not really legible...

Can you change the formatting of your section on the list command when you get the chance (aka ASAP :) ), and make a new PR (please use the master branch to create your PR and not the 2.0.10-dev branch, ok?)?

Thanks again!

**Comment by dbierer** [comment]
Andrew --
   
  
  
   
  
  
   Will do!
   
  
  
   
  
  
   --db
   
  
  
   
    On 05/06/2021 6:45 PM Andrew Caya ***@***.***> wrote:
   
   
    
   
   
    
   
   
   @dbierer Thought you had followed the syntax for Sphinx in the documentation, but I see it's not the case: https://linux-for-composer.readthedocs.io/en/latest/usage.html. Not really legible...
   Can you change the formatting of your section on the list command when you get the chance (aka ASAP :) ), and make a new PR (please use the master branch to create your PR and not the 2.0.10-dev branch, ok?)?
   Thanks again!

**Comment by andrewscaya** [comment]
Completed with PR #7.

@dbierer Thanks again!

**Pull request closed without merging**
